# Generated by Django 4.1.7 on 2023-02-16 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0004_alter_movie_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="orders",
            field=models.ManyToManyField(
                related_name="ordered_movies",
                through="movies.MovieOrder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
