# Generated by Django 4.1.7 on 2023-02-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_alter_movie_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieorder",
            name="buyed_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
